### PR TITLE
refactor to rails engine, update db config

### PR DESCRIPTION
**Pull request by crowesn**
fresh clone of repo, replaced most files with freshly generated engine.

### CODE REVIEW

**Comment by jamesvanmil** [comment]
Looking at this, I don't see that the old models have been removed... I think that's something that should be part of the pull. (e.g. lib/active_sierra/app/model/*)

**Comment by crowesn** [comment]
Oh I think I did bibview and neglected to update the others. You wanna
reject and I'll make another request?  How does that work?

**Comment by crowesn** [comment]
Updated all models to inherit from new SierraTable connector class. Fixed date on license

**Comment by jamesvanmil** [comment]
I've tested from larry and reviewed the code - looks good!

**Pull request merged**
